package com.springSecurity.controller;

import com.springSecurity.constants.ApplicationConstants;
import com.springSecurity.model.Customers;
import com.springSecurity.model.LoginRequestDTO;
import com.springSecurity.model.LoginResponseDTO;
import com.springSecurity.repository.CustomerRepository;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.security.Keys;
import lombok.RequiredArgsConstructor;
import org.springframework.core.env.Environment;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import javax.crypto.SecretKey;
import java.nio.charset.StandardCharsets;
import java.sql.Date;
import java.util.Optional;
import java.util.stream.Collectors;


@RestController
@RequiredArgsConstructor
public class UserController {

    private final CustomerRepository customerRepository;
    private final PasswordEncoder passwordEncoder;
    private final AuthenticationManager authenticationManager;
    private final Environment environment;

    @RequestMapping("/user")
    public Customers getDetailsAfterLogin(Authentication authentication) {
        Optional<Customers> customers = customerRepository.findByEmail(authentication.getName());
        return customers.orElse(null);
    }

    @PostMapping("/register")
    public ResponseEntity<String> registerUser(@RequestBody Customers customers) {
        try {
            String hashPwd = passwordEncoder.encode(customers.getPwd());
            customers.setPwd(hashPwd);
            customers.setCreateDt(new Date(System.currentTimeMillis()));
            Customers savedCustomer = customerRepository.save(customers);

            //In case save() customer is successful the returned object will going to have the id populated
            //with the new value which is generated by the database.

            if (savedCustomer.getId() > 0) {
                return ResponseEntity.status(HttpStatus.CREATED).body("Given user details are successfully registered.");
            } else {
                return ResponseEntity.status(HttpStatus.BAD_REQUEST).body("User Registration failed.");
            }
        } catch (Exception e) {
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                    .body("An exception occurred: " + e.getMessage());
        }
    }

    @PostMapping("/apiLogin")
    public ResponseEntity<LoginResponseDTO> apiLogin(@RequestBody LoginRequestDTO loginRequest) {
        String JWT = "";
        Authentication authentication = UsernamePasswordAuthenticationToken.unauthenticated(
                loginRequest.username(),
                loginRequest.password()
        );
        Authentication authenticationRes = authenticationManager.authenticate(authentication);
        if (null != authenticationRes &&
                authenticationRes.isAuthenticated()) {
            if (null != environment) {
                String secret = environment.getProperty(ApplicationConstants.JWT_SECRET_KEY,
                        ApplicationConstants.JWT_SECRET_DEFAULT_VALUE);
                SecretKey secretKey = Keys.hmacShaKeyFor(secret.getBytes(StandardCharsets.UTF_8));
                JWT = Jwts.builder().issuer("Eazy Bank").subject("JWT Token")
                        .claim("username", authenticationRes.getName())
                        .claim("authorities", authenticationRes.getAuthorities().stream().map(
                                GrantedAuthority::getAuthority
                        ).collect(Collectors.joining(",")))
                        .issuedAt(new java.util.Date())
                        .expiration(new java.util.Date((new java.util.Date()).getTime() + 30000000))
                        .signWith(secretKey)
                        .compact();
            }
        }
        return ResponseEntity.status(HttpStatus.OK).header(ApplicationConstants.JWT_HEADER, JWT)
                .body(new LoginResponseDTO(HttpStatus.OK.getReasonPhrase(), JWT));
    }
}
